#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        type: string
        example:
          "Bad Request"
  408:
    body:
      application/json:
        type: string
        example:
          "Request Timeout"
  500:
    body:
      application/json:
        type: string
        example:
          "Internal Server Error"