#%RAML 1.0 Trait
responses:
  400:
        body:
          application/json:
            type: string
            example: "Bad Request"
  403:
        body:
          application/json:
            type: string
            example: "Forbidden"